---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/dhaneshande/versioning.git
- name: resource-gist
  type: git
  source:
    uri: git@gist.github.com:c93fa4887517031f0482a5dd1bab5371.git
    branch: master
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEA3K78XNfUmkuD+Gcn7Z8ybJTEu5aIP8kBFPCI9bIGoVYyhUTo
      e9AqqIf/54RTTaRDDxUxUhgNG/eSYX2c1CQb3mcIWdJ1M6I6kvwYhOK5vlKgzFCc
      3s9Sin7bltTe7zrHcHD8xDyB++FDtVviBH9N9E07hn9mbsATN8nE0B/kL5vQpXsx
      7CO7gSgl/i46DHr97haRwCEDMAdYMBhMlCpAQCKl6TsZ3wM3KrV7RmsmFRSc8f3W
      eeybdgu/EkB77fgAgSMkekDZzWghjaKYdDj1hHqnhG0J5QEt3EIrk/P3X0mRgjPM
      MJNFvJVMSIkDsZPFpLDuAdJcGbD+sEtDN5IeawIDAQABAoIBADyFTLZVhnuuHAoi
      mCOllhmLDwz28nSztjU85gKjiQfz8LT1ueBCrYA8k+S1OHdBhhZ71GPULrwtwBo2
      ba0MHgx3KyYe/n9jjTbEJiFDYHceh/SgYvUD3HoY4jXSOTVYZFuk0N0sTuV52KzC
      /xAGraVDDQEMrVXQHTUeg3gkVtrrGQW8z6Rx+6ZeoDfZpHsZEsp/ENfsb/9IVTa6
      Adhz7bF0an/RWoypJ6AbiJpp+viWoDebAO8dx7OQ83raF1+9hIrUTJs3Ukp3tvQa
      hAsDI53AurnyYegmogSEI7OYB8++jn/llWwOGBJKRz+cAUDozUDEaBl1fBttAoEA
      0AMeqYECgYEA7hhlai8x4Kl1rjG8/c5zB8aUj2VJutUwsrzgWjszJAvlkIBUOKjB
      AYkt6sNRDge2zpUz5hU6E42u01Gt/edfGItbFEzbfoJNWAj99yxwYvaOHNkKJO60
      qc3hC+oGWKU2DE3hHeyeB5/izgAjnrLMDCopLnPMclf2uXpH5HdJYsECgYEA7Udk
      wWkG4IVO7OcQyYraZdvRyF6N9TDFvw8neRIxLd/41DpQLWaTvFfUueP22Y6321ls
      l9bZfVzLhY6rN0e/voyNWEytBeuZ7wYq5vd9YshuhZbRJ/TS+RCrnVMTGnbQEs7D
      12ua0pFKTtpulWVrLn7vts+mM894lHZN4MvIiCsCgYBy+/EuQLCT0QL2JysgX62J
      2csxHTdoNUEZcMHgkap3BA/Po0oJOuZK+ZblQ4JHhk4wojm4KhQsEUaW42Flt3Fj
      hxlrSlrOU9tKYr1Tu3BjOrMTF3Ygs+8n+jdu64w5D0B03L+VFgqToBGGbubE45BL
      Z6kPt/jKV9TdakKCAWG9gQKBgQCVZ6jnp+wun4IM5YnKfeX60SkM04zrYKSDI1Wl
      hHD3A9o4N+eYTsijhWJrEkGyx4y5T1tzWFNl/nIgTK8+ha0UnIe7m7wuyCULPoTx
      HdETzETbVRWp5Ryau4Zz74VN2pY14X+rOxQnlliFwkBzTYLpqf/iymlKok64nK14
      6JgCNQKBgEZN9ZmpDW4KyevXlPeRXCU2jg8ZJ2xtljGHmcfjfXbW7n1ThWUJtpMz
      tyxqm6HYd7XJxn63KB7ORJC/LccgLm5YPch7isnAfCNgu9ctFY2agKyGlMFuRNab
      826SqSOQzuis4/cVghHfjFltLpv9spB5nbah68SEjPHl5Ct4xECc
      -----END RSA PRIVATE KEY-----


jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-gist
  - task: bump-timestamp-file
    file: resource-tutorial/bump-timestamp-file.yml
  - put: resource-gist
    params: {repository: updated-gist}
- name: job-show-date
  plan:
  - get: resource-tutorial
  - get: resource-gist
    passed: [job-bump-date]
    trigger: true
  - task: show-date
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: resource-gist
      run:
        path: cat
        args: [resource-gist/bumpme]
