---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/dhaneshande/versioning.git

jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
  - task: bump-timestamp-file
    file: resource-tutorial/bump-timestamp-file.yml
- name: job-show-date
  plan:
  - get: resource-tutorial
  - get: resource-gist
    passed: [job-bump-date]
    trigger: true
  - task: show-date
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: resource-gist
      run:
        path: cat
        args: [resource-gist/bumpme]
